package hci2.group5.project.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import hci2.group5.project.dao.Building;
import hci2.group5.project.dao.Department;

import hci2.group5.project.dao.BuildingDao;
import hci2.group5.project.dao.DepartmentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig buildingDaoConfig;
    private final DaoConfig departmentDaoConfig;

    private final BuildingDao buildingDao;
    private final DepartmentDao departmentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        buildingDaoConfig = daoConfigMap.get(BuildingDao.class).clone();
        buildingDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        buildingDao = new BuildingDao(buildingDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);

        registerDao(Building.class, buildingDao);
        registerDao(Department.class, departmentDao);
    }
    
    public void clear() {
        buildingDaoConfig.getIdentityScope().clear();
        departmentDaoConfig.getIdentityScope().clear();
    }

    public BuildingDao getBuildingDao() {
        return buildingDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

}
