package hci2.group5.project.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import hci2.group5.project.dao.Faculty;
import hci2.group5.project.dao.Location;
import hci2.group5.project.dao.Building;
import hci2.group5.project.dao.Department;
import hci2.group5.project.dao.Library;

import hci2.group5.project.dao.FacultyDao;
import hci2.group5.project.dao.LocationDao;
import hci2.group5.project.dao.BuildingDao;
import hci2.group5.project.dao.DepartmentDao;
import hci2.group5.project.dao.LibraryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig facultyDaoConfig;
    private final DaoConfig locationDaoConfig;
    private final DaoConfig buildingDaoConfig;
    private final DaoConfig departmentDaoConfig;
    private final DaoConfig libraryDaoConfig;

    private final FacultyDao facultyDao;
    private final LocationDao locationDao;
    private final BuildingDao buildingDao;
    private final DepartmentDao departmentDao;
    private final LibraryDao libraryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        facultyDaoConfig = daoConfigMap.get(FacultyDao.class).clone();
        facultyDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        buildingDaoConfig = daoConfigMap.get(BuildingDao.class).clone();
        buildingDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        libraryDaoConfig = daoConfigMap.get(LibraryDao.class).clone();
        libraryDaoConfig.initIdentityScope(type);

        facultyDao = new FacultyDao(facultyDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);
        buildingDao = new BuildingDao(buildingDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        libraryDao = new LibraryDao(libraryDaoConfig, this);

        registerDao(Faculty.class, facultyDao);
        registerDao(Location.class, locationDao);
        registerDao(Building.class, buildingDao);
        registerDao(Department.class, departmentDao);
        registerDao(Library.class, libraryDao);
    }
    
    public void clear() {
        facultyDaoConfig.getIdentityScope().clear();
        locationDaoConfig.getIdentityScope().clear();
        buildingDaoConfig.getIdentityScope().clear();
        departmentDaoConfig.getIdentityScope().clear();
        libraryDaoConfig.getIdentityScope().clear();
    }

    public FacultyDao getFacultyDao() {
        return facultyDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public BuildingDao getBuildingDao() {
        return buildingDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public LibraryDao getLibraryDao() {
        return libraryDao;
    }

}
