package hci2.group5.project.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import hci2.group5.project.dao.Department;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DEPARTMENT.
*/
public class DepartmentDao extends AbstractDao<Department, Long> {

    public static final String TABLENAME = "DEPARTMENT";

    /**
     * Properties of entity Department.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FacultyId = new Property(1, long.class, "facultyId", false, "FACULTY_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property BuildingId = new Property(3, long.class, "buildingId", false, "BUILDING_ID");
    };

    private DaoSession daoSession;

    private Query<Department> building_DepartmentsQuery;

    public DepartmentDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DEPARTMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FACULTY_ID' INTEGER NOT NULL ," + // 1: facultyId
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'BUILDING_ID' INTEGER NOT NULL );"); // 3: buildingId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DEPARTMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Department entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFacultyId());
        stmt.bindString(3, entity.getName());
        stmt.bindLong(4, entity.getBuildingId());
    }

    @Override
    protected void attachEntity(Department entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Department readEntity(Cursor cursor, int offset) {
        Department entity = new Department( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // facultyId
            cursor.getString(offset + 2), // name
            cursor.getLong(offset + 3) // buildingId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Department entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFacultyId(cursor.getLong(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setBuildingId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Department entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Department entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "departments" to-many relationship of Building. */
    public List<Department> _queryBuilding_Departments(long buildingId) {
        synchronized (this) {
            if (building_DepartmentsQuery == null) {
                QueryBuilder<Department> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BuildingId.eq(null));
                queryBuilder.orderRaw("NAME ASC");
                building_DepartmentsQuery = queryBuilder.build();
            }
        }
        Query<Department> query = building_DepartmentsQuery.forCurrentThread();
        query.setParameter(0, buildingId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFacultyDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBuildingDao().getAllColumns());
            builder.append(" FROM DEPARTMENT T");
            builder.append(" LEFT JOIN FACULTY T0 ON T.'FACULTY_ID'=T0.'_id'");
            builder.append(" LEFT JOIN BUILDING T1 ON T.'BUILDING_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Department loadCurrentDeep(Cursor cursor, boolean lock) {
        Department entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Faculty faculty = loadCurrentOther(daoSession.getFacultyDao(), cursor, offset);
         if(faculty != null) {
            entity.setFaculty(faculty);
        }
        offset += daoSession.getFacultyDao().getAllColumns().length;

        Building building = loadCurrentOther(daoSession.getBuildingDao(), cursor, offset);
         if(building != null) {
            entity.setBuilding(building);
        }

        return entity;    
    }

    public Department loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Department> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Department> list = new ArrayList<Department>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Department> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Department> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
