package hci2.group5.project.dao;

import com.google.android.gms.maps.model.LatLng;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Long id;
    private double latitude;
    private double longitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, double latitude, double longitude) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    /**
     * @return an equivalent to Google map's LatLng instance
     */
    public LatLng toLatLng() {
        return new LatLng(getLatitude(), getLongitude());
    }
    // KEEP METHODS END

}
